### ISSUE TITLE
Status Tracking

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista-tutorial#53]
A single place to track progress

## Sections
- [x] 0. Getting Started (@akaszynski ) - PyVista for 3D Visualization within Python. (10 min for talk, 10 min for exercise)
  - [x] Section content
  - [x] Reviewed
- [x] 1. Basic usage (@akaszynski ) - Reading and plotting 3D data using ``examples`` module and external files.  (10 min for talk, 10 min for exercise)
  - [x] Section content
  - [x] Exercises
  - [x] Reviewed
- [ ] 2. What is a Mesh? (@banesullivan) - Learn the basics of the PyVista data types and how to open common 3D file formats to visualize the data in 3D (15 min for talk, 10 min for exercise)
  - [x] Section content
  - [x] Exercises
  - [x] Reviewed
- [ ] 3. Plotting Options and Animations (@banesullivan) - Demonstrate many features of the PyVista plotting API to create compelling 3D visualizations and touch on animations (10 min for talk, 10 min for exercise)
  - [x] Section content
  - [x] Exercises
  - [ ] Reviewed
- [ ] 4. Filters (@banesullivan) 
  - [x] Section content
  - [x] Exercises
  - [ ] Reviewed
- [x] 5. PyVista in Action (@tkoyama010) - Show how PyVista is already being used within several projects and can be used for all things visualization. (15 min for talk)
  - [x] Reviewed
- [ ] 6. PyVista & VTK (@banesullivan) - Show how PyVista uses VTK and how you can combine the best of both worlds! (10 minutes for talk, 10 minutes for exercise)
  - [x] Section content
  - [x] Exercises
  - [ ] Reviewed
- [x] 7. PyVista & Sphinx (@akaszynski) - Leverage PyVista to make some awesome interactive web documentation. (10 min for talk, 10 min for exercise)
  - [x] Section content
  - [x] Exercises
  - [x] Reviewed
- [x] 8. Widgets in PyVista (@tkoyama010) - Demonstrate how to use widgets in PyVista. (10 min for talk and 10 exercises)
  - [x] Section content
  - [x] Exercises
  - [x] Reviewed
- [x] 9. PyVista & Qt (@akaszynski ) - Demonstrate how to use PyVista to create standalone applications using pyinstaller and the Qt framework. (15 min for talk)
  - [x] Section content
  - [x] Exercises
  - [x] Reviewed

## Other

- [x] Overview/welcome page
- [x] Getting started with installation instructions
- [x] Switch pythreejs to panel
